import { Product } from "@/types/domain";
import { getAllProductImages } from "@/lib/product-images";

const allProductImages = getAllProductImages();

export const fallbackProducts: Product[] = [
  {
    id: "koko",
    slug: "koko",
    name: "Koko - 100% Millet",
    shortDescription: "African spiced hot cereal",
    longDescription:
      "Enjoy as a warm breakfast porridge or nourishing drink. Rich in flavor, warming, and nutritious.",
    category: "BREAKFAST",
    basePriceCents: 1299,
    imageUrl: "/assets/koko.jpeg",
    imageUrls: allProductImages,
    tags: ["No Preservatives", "All Natural", "Authentic Recipe", "Ready in 5 Minutes", "Naturally Gluten-Free"],
    ingredients: ["Millet", "Ginger", "Cloves", "Black Pepper"],
    servingSize: "1/4 cup (30g)",
    calories: 100,
    variants: [
      { id: "koko-400", label: "14.10 oz", size: "400 g", priceCents: 1299, sku: "KOKO-400G" }
    ]
  },
  {
    id: "shito",
    slug: "shito",
    name: "Hot Pepper Relish (Shito)",
    shortDescription: "Traditional West African shito",
    longDescription:
      "A rich, bold, and smoky relish made with real seafood, slow cooked for unforgettable flavor.",
    category: "CONDIMENT",
    basePriceCents: 1499,
    imageUrl: "/assets/hot%20pepper%20beef%20relish.jpeg",
    imageUrls: allProductImages,
    tags: ["Small Batch Slow Cooked", "Made With Real Seafood"],
    ingredients: ["Vegetable Oil", "Onions", "Dried Fish", "Dried Shrimp", "Fresh Ginger", "Powdered Dried Chili Pepper"],
    servingSize: "1 tbsp (15g)",
    calories: 60,
    variants: [
      { id: "shito-12", label: "12 oz", size: "340 g", priceCents: 1499, sku: "SHITO-12OZ" },
      { id: "shito-16", label: "16 oz", size: "454 g", priceCents: 1899, sku: "SHITO-16OZ" }
    ]
  },
  {
    id: "plantain-chips",
    slug: "plantain-chips",
    name: "Plantain Chips - Hot Pepper",
    shortDescription: "Premium African snack",
    longDescription:
      "Crispy, bold, irresistible chips made with real plantains and African spices for perfect crunch.",
    category: "SNACK",
    basePriceCents: 699,
    imageUrl: "/assets/plantain%20chips%20hot%20pepper.jpeg",
    imageUrls: allProductImages,
    tags: ["Made With Real Plantains", "No Artificial Colors", "Bold Flavor Perfect Crunch", "Gluten Free"],
    ingredients: [
      "Green Plantains",
      "Sunflower Oil",
      "Salt",
      "Cayenne Pepper",
      "Chili Pepper",
      "Onion Powder",
      "Paprika"
    ],
    servingSize: "1 oz (28g)",
    calories: 150,
    variants: [{ id: "plantain-5", label: "5 oz", size: "142 g", priceCents: 699, sku: "PLANTAIN-5OZ" }]
  },
  {
    id: "corn-lunch",
    slug: "corn-lunch",
    name: "Corn Lunch Flour",
    shortDescription: "Traditional fermented corn flour blend",
    longDescription: "A versatile pantry staple for making smooth and authentic Lunch with classic flavor.",
    category: "LUNCH",
    basePriceCents: 1099,
    imageUrl: "/assets/corn%20banku.jpeg",
    imageUrls: allProductImages,
    tags: ["Authentic", "Pantry Staple", "No Artificial Colors"],
    ingredients: ["Corn Flour", "Fermented Corn Blend"],
    servingSize: "1/4 cup (30g)",
    calories: 110,
    variants: [{ id: "corn-lunch-400", label: "14 oz", size: "400 g", priceCents: 1099, sku: "CORN-LUNCH-400G" }]
  },
  {
    id: "hot-pepper",
    slug: "hot-pepper",
    name: "Hot Pepper Blend",
    shortDescription: "Spicy pepper seasoning for bold meals",
    longDescription: "Bring heat and depth to soups, stews, marinades, and grilled dishes.",
    category: "CONDIMENT",
    basePriceCents: 999,
    imageUrl: "/assets/hot%20pepper.jpeg",
    imageUrls: allProductImages,
    tags: ["Bold Flavor", "Small Batch", "Heat Lovers"],
    ingredients: ["Chili Pepper", "Garlic", "Onion", "Salt"],
    servingSize: "1 tsp (5g)",
    calories: 15,
    variants: [{ id: "hot-pepper-8", label: "8 oz", size: "227 g", priceCents: 999, sku: "HOT-PEPPER-8OZ" }]
  },
  {
    id: "kulikuli",
    slug: "kulikuli",
    name: "Kulikuli Snack",
    shortDescription: "Crunchy peanut-based African snack",
    longDescription: "Enjoy a savory and crunchy snack with rich roasted peanut notes.",
    category: "SNACK",
    basePriceCents: 899,
    imageUrl: "/assets/kulikuli.jpeg",
    imageUrls: allProductImages,
    tags: ["Crunchy", "Roasted", "Traditional Recipe"],
    ingredients: ["Ground Peanuts", "Spices", "Salt"],
    servingSize: "1 oz (28g)",
    calories: 170,
    variants: [{ id: "kulikuli-6", label: "6 oz", size: "170 g", priceCents: 899, sku: "KULIKULI-6OZ" }]
  },
  {
    id: "nut-brown",
    slug: "nut-brown",
    name: "Nut Brown Cereal Mix",
    shortDescription: "Roasted grain mix for warm cereal",
    longDescription: "A hearty blend that cooks into a smooth and satisfying breakfast bowl.",
    category: "BREAKFAST",
    basePriceCents: 1199,
    imageUrl: "/assets/nut-brown.jpeg",
    imageUrls: allProductImages,
    tags: ["Hearty", "Roasted", "No Preservatives"],
    ingredients: ["Roasted Grains", "Natural Spices"],
    servingSize: "1/4 cup (30g)",
    calories: 120,
    variants: [{ id: "nut-brown-400", label: "14 oz", size: "400 g", priceCents: 1199, sku: "NUT-BROWN-400G" }]
  },
  {
    id: "plantain-chip",
    slug: "plantain-chip",
    name: "Plantain Chip Classic",
    shortDescription: "Crispy classic plantain chips",
    longDescription: "Lightly seasoned chips made from quality green plantains for everyday snacking.",
    category: "SNACK",
    basePriceCents: 699,
    imageUrl: "/assets/plantain%20chip.jpeg",
    imageUrls: allProductImages,
    tags: ["Crispy", "Snack Ready", "Gluten Free"],
    ingredients: ["Green Plantains", "Sunflower Oil", "Salt"],
    servingSize: "1 oz (28g)",
    calories: 150,
    variants: [{ id: "plantain-chip-5", label: "5 oz", size: "142 g", priceCents: 699, sku: "PLANTAIN-CHIP-5OZ" }]
  },
  {
    id: "plantain-cookies",
    slug: "plantain-cookies",
    name: "Plantain Cookies",
    shortDescription: "Sweet, crunchy plantain cookies",
    longDescription: "A delicious cookie treat with rich plantain flavor and a satisfying bite.",
    category: "SNACK",
    basePriceCents: 799,
    imageUrl: "/assets/plantain%20cookies.jpeg",
    imageUrls: allProductImages,
    tags: ["Baked", "Crunchy", "Family Favorite"],
    ingredients: ["Plantain Flour", "Cane Sugar", "Butter", "Natural Flavor"],
    servingSize: "1 oz (28g)",
    calories: 140,
    variants: [{ id: "plantain-cookies-6", label: "6 oz", size: "170 g", priceCents: 799, sku: "PLANTAIN-COOKIES-6OZ" }]
  },
  {
    id: "red-sorghum-lunch-flour",
    slug: "red-sorghum-lunch-flour",
    name: "Red Sorghum Lunch Flour",
    shortDescription: "Stone-milled red sorghum flour",
    longDescription: "Balanced texture and flavor for preparing wholesome Lunch and other traditional meals.",
    category: "LUNCH",
    basePriceCents: 1149,
    imageUrl: "/assets/red%20sorghum%20banku%20flour.jpeg",
    imageUrls: allProductImages,
    tags: ["Stone Milled", "Wholesome", "No Preservatives"],
    ingredients: ["Red Sorghum Flour"],
    servingSize: "1/4 cup (30g)",
    calories: 115,
    variants: [{ id: "red-sorghum-lunch-400", label: "14 oz", size: "400 g", priceCents: 1149, sku: "RED-SORGHUM-LUNCH-400G" }]
  },
  {
    id: "suya-spice",
    slug: "suya-spice",
    name: "Suya Spice",
    shortDescription: "Classic peanut-forward suya seasoning",
    longDescription: "Perfect for grilled meat, poultry, seafood, and roasted vegetables.",
    category: "CONDIMENT",
    basePriceCents: 999,
    imageUrl: "/assets/suya%20spice.jpeg",
    imageUrls: allProductImages,
    tags: ["Savory", "Peanut Forward", "Grill Ready"],
    ingredients: ["Ground Peanuts", "Ginger", "Paprika", "Chili Pepper", "Salt"],
    servingSize: "1 tsp (5g)",
    calories: 20,
    variants: [{ id: "suya-spice-8", label: "8 oz", size: "227 g", priceCents: 999, sku: "SUYA-SPICE-8OZ" }]
  },
  {
    id: "white-sorghum-lunch-flour",
    slug: "white-sorghum-lunch-flour",
    name: "White Sorghum Lunch Flour",
    shortDescription: "Fine white sorghum flour blend",
    longDescription: "Smooth and easy to prepare, ideal for authentic meals and creative recipes.",
    category: "LUNCH",
    basePriceCents: 1149,
    imageUrl: "/assets/white%20sorghum%20banku%20flour.jpeg",
    imageUrls: allProductImages,
    tags: ["Fine Milled", "Authentic", "Kitchen Essential"],
    ingredients: ["White Sorghum Flour"],
    servingSize: "1/4 cup (30g)",
    calories: 112,
    variants: [{ id: "white-sorghum-lunch-400", label: "14 oz", size: "400 g", priceCents: 1149, sku: "WHITE-SORGHUM-LUNCH-400G" }]
  }
];
